### ISSUE TITLE
SPHttpClient is not assignable to parameter of type SPHttpClient

### ISSUE THREAD

**Issue by hasan-abul** [SumitKanchan4/SPFxImageGallery#1]
@SumitKanchan4 

Hello Sumit,

Thanks for the SPFXhelper, I am trying use SPFxImageGallery after gulp it showing the below error. Sorry for the basic question i am very new to SPFX. Many thanks in advance for your help.

![image](https://user-images.githubusercontent.com/33178971/32222697-5a0bdf72-be4b-11e7-8a9d-4380668f7525.png)

**Comment by SumitKanchan4** [comment]
Hi Hasan,

Sorry for the late reply.Thanks for using SPFxhelper. Will love to hear your feedback on this. 

For the issue you reported, I have updated the code please have the latest version and mark it as close if it resolves your issue else let me know if the issue still exists.

Regards,
Sumit Kanchan

**Comment by hasan-abul** [comment]
@SumitKanchan4 

Hi Sumit,

Many thanks for the reply. Downloaded the latest version. Web-part compiled with no error. thanks for that.

Steps:
1. Downloaded the latest version
2. npm install
3. gulp serve (Executed successfully with no errors)
4. Opened another tab and login to my office 365 website
    https://mysite.sharepoint.com/_layouts/15/workbench.aspx
    Picture library loaded successfully in the dropdown
     All went fine 
5. No picture got loaded in the webpart library. It's keep loading.. 

Please let me know is there any steps i am missing here.

Thanks,
Hassan

**Comment by hasan-abul** [comment]
@SumitKanchan4 

Hi Sumit,

Many thanks for the reply. Downloaded the latest version. Web-part compiled with no error. thanks for that.

Steps:
1. Downloaded the latest version
2. npm install
3. gulp serve (Executed successfully with no errors)
4. Opened another tab and login to my office 365 website
    https://mysite.sharepoint.com/_layouts/15/workbench.aspx
    Picture library loaded successfully in the dropdown
     All went fine 
5. No picture got loaded in the webpart. It's keep loading.. 

Please let me know is there any steps i am missing here.

Thanks,
Hassan

**Comment by hasan-abul** [comment]
@SumitKanchan4

Hello Sumit,

Found the issue. In SPFXHelper module, Files like SPFieldOperations.js, SPListOperation.js, etc., are using function **isStringNullOrEmpy**, I replaced it with **isStringNullOrEmpty** everything working fine.

Thanks,
Hassan

**Comment by hasan-abul** [comment]
@SumitKanchan4

Hello Sumit,

Found the issue. In SPFXHelper module, Files like SPFieldOperations.js, SPListOperation.js, etc., are using function **isStringNullOrEmpy**, I replaced it with **isStringNullOrEmpty** everything working fine.

Thanks,
Hassan

**Comment by SumitKanchan4** [comment]
This has been resolved in the latest version of SPFxHelper
