### ISSUE TITLE
WebPart Configuration DropDown Menu not working

### ISSUE THREAD

**Issue by zahrajuma** [SumitKanchan4/SPFxImageGallery#2]
Great SharePoint widget but I am facing an issue while using.

When adding the web part to a page on my SharePoint site, when trying to configure it to show the pictures from a Document Library, the option to select the document library is somehow stuck? 

It doesn't let me choose anything and it just stays blank. 

Please advise.

**Comment by SumitKanchan4** [comment]
Hi, A new version has been updated, please get the latest package/code and try again. And please comment if you still feel the issue

**Comment by SumitKanchan4** [comment]
Closing the issue as it has been resolved in the version 2.0.0.0
